const state={mode:'login',user:null,dreams:[],days:30,tags:new Set(),editing:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const api=async(path,options={})=>{const res=await fetch(path,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});if(!res.ok){let body={};try{body=await res.json()}catch{}throw new Error(body.error||`请求失败 ${res.status}`)}if(res.headers.get('content-type')?.includes('application/json')){const body=await res.json();return body.data}return res};
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const today=()=>new Date().toISOString().slice(0,10);
const isoLocal=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)};
function message(id,text,error=false){const el=$(id);el.textContent=text;el.style.color=error?'#b85866':'#6f55d9'}
async function init(){ $('#dream-date').value=today();$('#wake-time').value=isoLocal();$('#dream-clarity').addEventListener('input',e=>$('#clarity-output').textContent=e.target.value);$$('[data-auth-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.authMode));$('#auth-form').onsubmit=authSubmit;$('#logout').onclick=logout;$('#dream-form').onsubmit=saveDream;$('#dream-cancel').onclick=resetForm;$('#custom-tag').onkeydown=customTag;$('#dream-content').oninput=debounce(suggest,350);$('#dream-title').oninput=debounce(suggest,350);$('#dream-search').oninput=debounce(loadDreams,250);$('#range-select').onchange=e=>{state.days=+e.target.value;loadDreams();loadAnalysis()};$$('.range-pills button').forEach(b=>b.onclick=()=>{state.days=+b.dataset.days;$$('.range-pills button').forEach(x=>x.classList.remove('active'));b.classList.add('active');loadAnalysis()});$('#refresh-report').onclick=refreshReport;$('#export-md').onclick=()=>download('/api/v1/export/markdown');$('#export-json').onclick=()=>download('/api/v1/export/json');try{state.user=await api('/api/v1/session');showWorkspace()}catch{showAuth()}}
function setMode(mode){state.mode=mode;$$('[data-auth-mode]').forEach(b=>b.classList.toggle('active',b.dataset.authMode===mode));$('#auth-name-wrap').classList.toggle('hidden',mode!=='register');$('#auth-submit').textContent=mode==='register'?'创建我的工作台':'进入我的工作台';message('#auth-message','')}
async function authSubmit(e){e.preventDefault();const payload={email:$('#auth-email').value,name:$('#auth-name').value,password:$('#auth-password').value};try{state.user=await api(`/api/v1/auth/${state.mode}`,{method:'POST',body:JSON.stringify(payload)}).then(x=>x.user);showWorkspace()}catch(err){message('#auth-message',err.message,true)}}
function showAuth(){$('#auth-panel').classList.remove('hidden');$('#workspace').classList.add('hidden');$('#account-name').textContent='未登录';$('#logout').classList.add('hidden')}
async function showWorkspace(){$('#auth-panel').classList.add('hidden');$('#workspace').classList.remove('hidden');$('#account-name').textContent=state.user.display_name;$('#hero-name').textContent=state.user.display_name.toUpperCase();$('#logout').classList.remove('hidden');await Promise.all([loadDreams(),loadAnalysis(),loadReport()])}
async function logout(){await api('/api/v1/auth/logout',{method:'POST'}).catch(()=>{});state.user=null;showAuth()}
async function loadDreams(){if(!state.user)return;const q=encodeURIComponent($('#dream-search').value||'');try{state.dreams=await api(`/api/v1/dreams?days=${state.days}&q=${q}`);renderDreams();$('#hero-count').textContent=state.dreams.length}catch(err){message('#dream-message',err.message,true)}}
function renderDreams(){const el=$('#dream-list');if(!state.dreams.length){el.innerHTML='<div class="empty">还没有梦境记录。今天醒来后，试着写下一句。</div>';return}el.innerHTML=state.dreams.map(d=>`<article class="dream-card" data-id="${esc(d.id)}"><span class="date">${esc(d.dream_date.slice(0,10))} · ${esc(d.emotion)}</span><h3>${esc(d.title)}</h3><p>${esc(d.content)}</p><div class="dream-meta"><span>${d.sleep_hours} 小时 · 清晰度 ${d.clarity}</span><span class="theme-inline">${esc((d.themes||[]).map(x=>x.name).slice(0,2).join(' · ')||'待形成主题')}</span></div></article>`).join('');$$('.dream-card').forEach(c=>c.onclick=()=>editDream(c.dataset.id))}
async function editDream(id){const d=state.dreams.find(x=>x.id===id);if(!d)return;state.editing=id;$('#dream-id').value=id;$('#dream-title').value=d.title;$('#dream-content').value=d.content;$('#dream-date').value=d.dream_date.slice(0,10);const wake=new Date(d.wake_time);wake.setMinutes(wake.getMinutes()-wake.getTimezoneOffset());$('#wake-time').value=wake.toISOString().slice(0,16);$('#sleep-hours').value=d.sleep_hours;$('#dream-clarity').value=d.clarity;$('#clarity-output').textContent=d.clarity;$('#dream-emotion').value=d.emotion;$('#remember-detail').checked=d.remember_detail;state.tags=new Set(d.tags||[]);renderTags();$('#dream-submit-text').textContent='更新这段记忆';$('#dream-cancel').classList.remove('hidden');$('#capture').scrollIntoView({behavior:'smooth'})}
function resetForm(){state.editing=null;$('#dream-form').reset();$('#dream-date').value=today();$('#wake-time').value=isoLocal();$('#dream-clarity').value=6;$('#clarity-output').textContent='6';state.tags=new Set();renderTags();$('#dream-submit-text').textContent='保存这段记忆';$('#dream-cancel').classList.add('hidden');message('#dream-message','')}
async function saveDream(e){e.preventDefault();const payload={title:$('#dream-title').value,content:$('#dream-content').value,dream_date:new Date(`${$('#dream-date').value}T00:00:00Z`).toISOString(),wake_time:new Date($('#wake-time').value).toISOString(),sleep_hours:+$('#sleep-hours').value,clarity:+$('#dream-clarity').value,emotion:$('#dream-emotion').value,remember_detail:$('#remember-detail').checked,tags:[...state.tags]};try{if(state.editing)await api(`/api/v1/dreams/${state.editing}`,{method:'PUT',body:JSON.stringify(payload)});else await api('/api/v1/dreams',{method:'POST',body:JSON.stringify(payload)});message('#dream-message','已保存，主题分析也更新了。');resetForm();await Promise.all([loadDreams(),loadAnalysis(),loadReport()])}catch(err){message('#dream-message',err.message,true)}}
async function suggest(){try{const title=$('#dream-title').value,content=$('#dream-content').value;if(!title&&!content)return;const tags=await api(`/api/v1/elements/suggestions?title=${encodeURIComponent(title)}&content=${encodeURIComponent(content)}`);renderTags(tags)}catch{}}
function renderTags(suggestions){const values=suggestions||[...state.tags].map(name=>({name}));if(suggestions)values.forEach(x=>{if(state.tags.has(x.name))x.selected=true});$('#tag-chips').innerHTML=values.map(x=>`<button type="button" class="chip ${state.tags.has(x.name)?'selected':''}" data-tag="${esc(x.name)}">${esc(x.name)}${x.count?` · ${x.count}`:''}</button>`).join('');$$('.chip').forEach(b=>b.onclick=()=>{const tag=b.dataset.tag;if(state.tags.has(tag))state.tags.delete(tag);else state.tags.add(tag);renderTags()})}
function customTag(e){if(e.key!=='Enter')return;e.preventDefault();const value=e.target.value.trim();if(value)state.tags.add(value);e.target.value='';renderTags()}
async function loadAnalysis(){if(!state.user)return;try{const query=`?days=${state.days}`;const [overview,themes,emotions,words,mood,sleep,pairs,phrases,signals,review]=await Promise.all([api(`/api/v1/analysis/overview${query}`),api(`/api/v1/analysis/themes${query}`),api(`/api/v1/analysis/emotions${query}`),api(`/api/v1/analysis/wordcloud${query}`),api(`/api/v1/analysis/mood${query}`),api(`/api/v1/analysis/sleep-contrast${query}`),api(`/api/v1/analysis/theme-pairs${query}`),api(`/api/v1/analysis/phrases${query}`),api(`/api/v1/analysis/signals${query}`),api(`/api/v1/analysis/review${query}`)]);renderOverview(overview);renderThemes(themes);renderEmotions(emotions);renderWords(words);renderMood(mood);renderSleepContrast(sleep);renderThemePairs(pairs);renderPhrases(phrases);renderSignals(signals);renderReview(review)}catch(err){console.error(err)}}
function renderOverview(o){const cards=[['记录总数',o.total_dreams,'条'],['平均清晰度',o.average_clarity,'/ 10'],['平均睡眠',o.average_sleep,'小时'],['细节记忆率',`${Math.round(o.remember_rate*100)}%`,'']];$('#overview-cards').innerHTML=cards.map(x=>`<div class="stat"><b>${esc(x[1])}</b><span>${x[0]} ${x[2]}</span></div>`).join('');$('#insight-list').innerHTML=(o.insights||[]).map(x=>`<article class="insight"><h4>${esc(x.title)}</h4><p>${esc(x.detail)}</p></article>`).join('')}
function renderThemes(items){const max=Math.max(...items.map(x=>x.count),1);$('#theme-bars').innerHTML=items.length?items.map(x=>`<div class="bar-row"><span>${esc(x.name)}</span><div class="bar-track"><div class="bar-fill" style="width:${x.count/max*100}%"></div></div><b>${x.count}</b></div>`).join(''):'<div class="empty">主题会在记录积累后出现。</div>'}
function renderEmotions(data){const points=data.points||[];const max=Math.max(...points.map(x=>x.intensity),1);$('#emotion-chart').innerHTML=points.slice(-18).map(x=>`<div class="emotion-point" style="height:${Math.max(10,x.intensity/max*125)}px" data-label="${esc(x.date.slice(5))}" title="${esc(x.emotion)} · ${x.intensity}"></div>`).join('')||'<div class="empty">等待情绪时间序列</div>';$('#sleep-buckets').innerHTML=Object.entries(data.sleep_buckets||{}).map(([k,v])=>`<div class="sleep-bucket"><span>${esc(k)}</span><b>${v.clarity_avg||'—'}</b><small>平均清晰度</small></div>`).join('');$('#correlation').textContent=`睡眠 / 清晰度相关 ${data.sleep_clarity_correlation||'—'}`}
function renderWords(words){$('#word-cloud').innerHTML=words.length?words.map((x,i)=>`<span style="font-size:${14+Math.min(22,x.weight/4)}px;opacity:${1-i/words.length*.45}">${esc(x.word)}</span>`).join(''):'<div class="empty">再写几段，词语会慢慢长出来。</div>'}
function renderMood(report){$('#mood-report').innerHTML=report.observations?.length?`<p>主导情绪：<strong>${esc(report.dominant)}</strong> · 平均强度 ${report.average_score}</p><p>峰值：${esc(report.peak_date||'—')} / ${esc(report.peak_emotion||'—')}</p><ul>${(report.interpretation||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<div class="empty">积累记录后会出现情绪解释。</div>'}
function renderSleepContrast(groups){$('#sleep-contrast').innerHTML=groups.map(x=>`<div class="mini-row"><span>${esc(x.name)}</span><b>${x.count} 条</b><small>清晰度 ${x.average_clarity||'—'} · ${esc(x.top_emotion||'—')}</small></div>`).join('')}
function renderThemePairs(pairs){$('#theme-pairs').innerHTML=pairs.length?pairs.slice(0,6).map(x=>`<div class="mini-row"><span>${esc(x.left)} + ${esc(x.right)}</span><b>${x.count}</b><small>共现率 ${x.jaccard}</small></div>`).join(''):'<div class="empty">还没有足够的重复主题。</div>'}
function renderPhrases(phrases){$('#phrase-list').innerHTML=phrases.length?phrases.slice(0,8).map(x=>`<span class="phrase-pill">${esc(x.text)} · ${x.distinct_days} 天</span>`).join(''):'<div class="empty">跨日期短语会在记录积累后出现。</div>'}
function renderSignals(data){const change=data.count_change>0?`增加 ${data.count_change}`:data.count_change<0?`减少 ${Math.abs(data.count_change)}`:'没有变化';$('#signal-card').innerHTML=`<div class="signal-grid"><div><b>${data.recorded_days}/${data.coverage_days}</b><small>有记录的天数</small></div><div><b>${change}</b><small>记录数量变化</small></div><div><b>${data.current_clarity||'—'}</b><small>近期平均清晰度</small></div><div><b>${data.current_sleep||'—'}</b><small>近期平均睡眠</small></div></div><div class="signal-columns"><div><h4>增加的主题</h4>${(data.growing_themes||[]).slice(0,4).map(x=>`<p>${esc(x.name)} <strong>+${x.change}</strong></p>`).join('')||'<p>暂未发现明显增加</p>'}</div><div><h4>值得留意</h4>${(data.alerts||[]).concat(data.recommendations||[]).slice(0,4).map(x=>`<p>${esc(x)}</p>`).join('')||'<p>继续记录，变化会逐渐显现。</p>'}</div></div>`}
function renderReview(data){$('#review-card').innerHTML=`<div class="review-heading"><div><p class="eyebrow">WINDOW REVIEW</p><h3>${esc(data.headline)}</h3><p>${esc(data.subheadline)}</p></div><span class="review-confidence">${esc(data.confidence)}</span></div><div class="review-facts">${(data.facts||[]).slice(0,5).map(x=>`<div><b>${esc(x.value)}</b><small>${esc(x.label)} · ${esc(x.note)}</small></div>`).join('')}</div><div class="review-focus"><strong>下一步回看</strong>${(data.focus||[]).slice(0,3).map(x=>`<p>${esc(x.question)} <small>${esc(x.source)}</small></p>`).join('')}</div>`}
async function loadReport(){try{const report=await api('/api/v1/reports/weekly');renderReport(report)}catch(err){console.error(err)}}
function renderReport(r){$('#report-card').innerHTML=`<div class="report-flex"><div><p class="eyebrow" style="color:#f4c4aa">${esc(r.week_start.slice(0,10))} — ${esc(r.week_end.slice(0,10))}</p><h3>${esc(r.summary)}</h3><p>本周共记录 <strong>${r.total_dreams}</strong> 条 · 平均睡眠 <strong>${r.avg_sleep||'—'}</strong> 小时 · 平均清晰度 <strong>${r.avg_clarity||'—'}</strong> 分</p><p class="report-themes">${esc((r.top_themes||[]).map(x=>x.name).join('  /  ')||'主题还在形成')}</p></div><div><p class="eyebrow" style="color:#f4c4aa">给下周的建议</p><ul>${(r.suggestions||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></div>`}
async function refreshReport(){try{const report=await api('/api/v1/reports/refresh',{method:'POST'});renderReport(report)}catch(err){message('#dream-message',err.message,true)}}
function download(path){window.location.href=path}
function debounce(fn,wait){let timer;return(...args)=>{clearTimeout(timer);timer=setTimeout(()=>fn(...args),wait)}}
init();
